
[[redirects]]
  from = "/api/*"
  to = "http://139.59.131.160:4000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "http://139.59.131.160:4000/uploads/:splat"
  status = 200
  force = true



[[redirects]]
  from = "/auth/*"
  to = "http://139.59.131.160:4000/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
