
[[redirects]]
  from = "/api/*"
  to = "https://slourp.tk/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://slourp.tk/uploads/:splat"
  status = 200
  force = true



[[redirects]]
  from = "/auth/*"
  to = "https://slourp.tk/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
